name: GiddyUp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cowboysounds:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Check this bitch out
        uses: actions/checkout@v6

      - name: Turn on Mambo Number ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Claim dependencies on taxes
        run: npm ci

      - name: Brush everything under the bed
        run: npm run lint

      - name: Definitely don't cheat on tests
        run: npm test
