name: Rikes Raggy

on:
  workflow_run:
    workflows: ["Generate New Tag if Needed and Release"]
    types:
      - completed
    branches:
      - main

jobs:
  yeetasaurusrex:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.NPM_GITHUB_CD_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Ship it
        run: |
          npm publish --access public --//registry.npmjs.org/:_authToken=${TOKEN}
